2022-05-31 01:04:20,927 INFO [test01.py(test01:27)] - 正在执行调用执行数据：{'path': '/api/sys/login', 'method': 'post', 'headers': {'Content-Type': 'application/json'}, 'param_type': 'json', 'params': {'mobile': '13800000002', 'password': '123456'}, 'expect': {'code': 200, 'result': {'success': True, 'code': 100001, 'message': '操作成功！'}}, 'x_y': [2, 12]}
2022-05-31 01:04:20,927 INFO [api.py(run_method:57)] - 正在调用运行接口方法
2022-05-31 01:04:20,927 INFO [api.py(_post:39)] - 正在调用post请求方法
2022-05-31 01:04:21,040 INFO [common_assert.py(common_assert:16)] - 正在调用断言公共方法
2022-05-31 01:04:21,059 ERROR [test01.py(test01:39)] - 错误，原因：错误！响应 code：10000 预期 code：100001
2022-05-31 01:04:21,194 INFO [test01.py(test01:27)] - 正在执行调用执行数据：{'path': '/api/sys/login', 'method': 'post', 'headers': {'Content-Type': 'application/json'}, 'param_type': 'json', 'params': {'mobile': 'itheima', 'password': '123456'}, 'expect': {'code': 200, 'result': {'success': False, 'code': 20001, 'message': '用户名或密码错误'}}, 'x_y': [6, 12]}
2022-05-31 01:04:21,195 INFO [api.py(run_method:57)] - 正在调用运行接口方法
2022-05-31 01:04:21,195 INFO [api.py(_post:39)] - 正在调用post请求方法
2022-05-31 01:04:21,267 INFO [common_assert.py(common_assert:16)] - 正在调用断言公共方法
2022-05-31 01:04:21,291 INFO [test01.py(test01:27)] - 正在执行调用执行数据：{'path': '/api/sys/login', 'method': 'post', 'headers': {'Content-Type': 'application/json'}, 'param_type': 'json', 'params': {'mobile': '13800000002', 'password': ''}, 'expect': {'code': 200, 'result': {'success': False, 'code': 20001, 'message': '用户名或密码错误'}}, 'x_y': [7, 12]}
2022-05-31 01:04:21,291 INFO [api.py(run_method:57)] - 正在调用运行接口方法
2022-05-31 01:04:21,291 INFO [api.py(_post:39)] - 正在调用post请求方法
2022-05-31 01:04:21,377 INFO [common_assert.py(common_assert:16)] - 正在调用断言公共方法
2022-05-31 01:08:25,243 INFO [test01.py(test01:27)] - 正在执行调用执行数据：{'path': '/api/sys/login', 'method': 'post', 'headers': {'Content-Type': 'application/json'}, 'param_type': 'json', 'params': {'mobile': '13800000002', 'password': '123456'}, 'expect': {'code': 200, 'result': {'success': True, 'code': 100001, 'message': '操作成功！'}}, 'x_y': [2, 12]}
2022-05-31 01:08:25,243 INFO [api.py(run_method:57)] - 正在调用运行接口方法
2022-05-31 01:08:25,243 INFO [api.py(_post:39)] - 正在调用post请求方法
2022-05-31 01:08:25,688 INFO [common_assert.py(common_assert:16)] - 正在调用断言公共方法
2022-05-31 01:08:25,708 ERROR [test01.py(test01:39)] - 错误，原因：错误！响应 code：10000 预期 code：100001
2022-05-31 01:08:25,837 INFO [test01.py(test01:27)] - 正在执行调用执行数据：{'path': '/api/sys/login', 'method': 'post', 'headers': {'Content-Type': 'application/json'}, 'param_type': 'json', 'params': {'mobile': 'itheima', 'password': '123456'}, 'expect': {'code': 200, 'result': {'success': False, 'code': 20001, 'message': '用户名或密码错误'}}, 'x_y': [6, 12]}
2022-05-31 01:08:25,837 INFO [api.py(run_method:57)] - 正在调用运行接口方法
2022-05-31 01:08:25,837 INFO [api.py(_post:39)] - 正在调用post请求方法
2022-05-31 01:08:25,920 INFO [common_assert.py(common_assert:16)] - 正在调用断言公共方法
2022-05-31 01:08:25,945 INFO [test01.py(test01:27)] - 正在执行调用执行数据：{'path': '/api/sys/login', 'method': 'post', 'headers': {'Content-Type': 'application/json'}, 'param_type': 'json', 'params': {'mobile': '13800000002', 'password': ''}, 'expect': {'code': 200, 'result': {'success': False, 'code': 20001, 'message': '用户名或密码错误'}}, 'x_y': [7, 12]}
2022-05-31 01:08:25,945 INFO [api.py(run_method:57)] - 正在调用运行接口方法
2022-05-31 01:08:25,945 INFO [api.py(_post:39)] - 正在调用post请求方法
2022-05-31 01:08:26,060 INFO [common_assert.py(common_assert:16)] - 正在调用断言公共方法
2022-05-31 01:09:01,971 INFO [test01.py(test01:27)] - 正在执行调用执行数据：{'path': '/api/sys/login', 'method': 'post', 'headers': {'Content-Type': 'application/json'}, 'param_type': 'json', 'params': {'mobile': '13800000002', 'password': '123456'}, 'expect': {'code': 200, 'result': {'success': True, 'code': 100001, 'message': '操作成功！'}}, 'x_y': [2, 12]}
2022-05-31 01:09:01,971 INFO [api.py(run_method:57)] - 正在调用运行接口方法
2022-05-31 01:09:01,971 INFO [api.py(_post:39)] - 正在调用post请求方法
2022-05-31 01:09:02,082 INFO [common_assert.py(common_assert:16)] - 正在调用断言公共方法
2022-05-31 01:09:02,105 ERROR [test01.py(test01:39)] - 错误，原因：错误！响应 code：10000 预期 code：100001
2022-05-31 01:09:02,232 INFO [test01.py(test01:27)] - 正在执行调用执行数据：{'path': '/api/sys/login', 'method': 'post', 'headers': {'Content-Type': 'application/json'}, 'param_type': 'json', 'params': {'mobile': 'itheima', 'password': '123456'}, 'expect': {'code': 200, 'result': {'success': False, 'code': 20001, 'message': '用户名或密码错误'}}, 'x_y': [6, 12]}
2022-05-31 01:09:02,232 INFO [api.py(run_method:57)] - 正在调用运行接口方法
2022-05-31 01:09:02,232 INFO [api.py(_post:39)] - 正在调用post请求方法
2022-05-31 01:09:02,307 INFO [common_assert.py(common_assert:16)] - 正在调用断言公共方法
2022-05-31 01:09:02,331 INFO [test01.py(test01:27)] - 正在执行调用执行数据：{'path': '/api/sys/login', 'method': 'post', 'headers': {'Content-Type': 'application/json'}, 'param_type': 'json', 'params': {'mobile': '13800000002', 'password': ''}, 'expect': {'code': 200, 'result': {'success': False, 'code': 20001, 'message': '用户名或密码错误'}}, 'x_y': [7, 12]}
2022-05-31 01:09:02,331 INFO [api.py(run_method:57)] - 正在调用运行接口方法
2022-05-31 01:09:02,332 INFO [api.py(_post:39)] - 正在调用post请求方法
2022-05-31 01:09:02,435 INFO [common_assert.py(common_assert:16)] - 正在调用断言公共方法
2022-05-31 01:10:23,194 INFO [test01.py(test01:27)] - 正在执行调用执行数据：{'path': '/api/sys/login', 'method': 'post', 'headers': {'Content-Type': 'application/json'}, 'param_type': 'json', 'params': {'mobile': '13800000002', 'password': '123456'}, 'expect': {'code': 200, 'result': {'success': True, 'code': 100001, 'message': '操作成功！'}}, 'x_y': [2, 12]}
2022-05-31 01:10:23,194 INFO [api.py(run_method:57)] - 正在调用运行接口方法
2022-05-31 01:10:23,194 INFO [api.py(_post:39)] - 正在调用post请求方法
2022-05-31 01:10:23,548 INFO [common_assert.py(common_assert:16)] - 正在调用断言公共方法
2022-05-31 01:10:23,570 ERROR [test01.py(test01:39)] - 错误，原因：错误！响应 code：10000 预期 code：100001
2022-05-31 01:10:23,709 INFO [test01.py(test01:27)] - 正在执行调用执行数据：{'path': '/api/sys/login', 'method': 'post', 'headers': {'Content-Type': 'application/json'}, 'param_type': 'json', 'params': {'mobile': 'itheima', 'password': '123456'}, 'expect': {'code': 200, 'result': {'success': False, 'code': 20001, 'message': '用户名或密码错误'}}, 'x_y': [6, 12]}
2022-05-31 01:10:23,709 INFO [api.py(run_method:57)] - 正在调用运行接口方法
2022-05-31 01:10:23,709 INFO [api.py(_post:39)] - 正在调用post请求方法
2022-05-31 01:10:23,830 INFO [common_assert.py(common_assert:16)] - 正在调用断言公共方法
2022-05-31 01:10:23,853 INFO [test01.py(test01:27)] - 正在执行调用执行数据：{'path': '/api/sys/login', 'method': 'post', 'headers': {'Content-Type': 'application/json'}, 'param_type': 'json', 'params': {'mobile': '13800000002', 'password': ''}, 'expect': {'code': 200, 'result': {'success': False, 'code': 20001, 'message': '用户名或密码错误'}}, 'x_y': [7, 12]}
2022-05-31 01:10:23,853 INFO [api.py(run_method:57)] - 正在调用运行接口方法
2022-05-31 01:10:23,853 INFO [api.py(_post:39)] - 正在调用post请求方法
2022-05-31 01:10:23,943 INFO [common_assert.py(common_assert:16)] - 正在调用断言公共方法
2022-05-31 01:14:57,727 INFO [test01.py(test01:27)] - 正在执行调用执行数据：{'path': '/api/sys/login', 'method': 'post', 'headers': {'Content-Type': 'application/json'}, 'param_type': 'json', 'params': {'mobile': '13800000002', 'password': '654321'}, 'expect': {'code': 200, 'result': {'success': True, 'code': 100001, 'message': '操作成功！'}}, 'x_y': [2, 12]}
2022-05-31 01:14:57,727 INFO [api.py(run_method:57)] - 正在调用运行接口方法
2022-05-31 01:14:57,727 INFO [api.py(_post:39)] - 正在调用post请求方法
2022-05-31 01:14:58,024 INFO [common_assert.py(common_assert:16)] - 正在调用断言公共方法
2022-05-31 01:14:58,039 ERROR [test01.py(test01:39)] - 错误，原因：错误！响应 success：False 预期 success：True
2022-05-31 01:14:58,164 INFO [test01.py(test01:27)] - 正在执行调用执行数据：{'path': '/api/sys/login', 'method': 'post', 'headers': {'Content-Type': 'application/json'}, 'param_type': 'json', 'params': {'mobile': 'itheima', 'password': '123456'}, 'expect': {'code': 200, 'result': {'success': False, 'code': 20001, 'message': '用户名或密码错误'}}, 'x_y': [6, 12]}
2022-05-31 01:14:58,164 INFO [api.py(run_method:57)] - 正在调用运行接口方法
2022-05-31 01:14:58,164 INFO [api.py(_post:39)] - 正在调用post请求方法
2022-05-31 01:14:58,244 INFO [common_assert.py(common_assert:16)] - 正在调用断言公共方法
2022-05-31 01:14:58,275 INFO [test01.py(test01:27)] - 正在执行调用执行数据：{'path': '/api/sys/login', 'method': 'post', 'headers': {'Content-Type': 'application/json'}, 'param_type': 'json', 'params': {'mobile': '13800000002', 'password': ''}, 'expect': {'code': 200, 'result': {'success': False, 'code': 20001, 'message': '用户名或密码错误'}}, 'x_y': [7, 12]}
2022-05-31 01:14:58,275 INFO [api.py(run_method:57)] - 正在调用运行接口方法
2022-05-31 01:14:58,275 INFO [api.py(_post:39)] - 正在调用post请求方法
2022-05-31 01:14:58,369 INFO [common_assert.py(common_assert:16)] - 正在调用断言公共方法
2022-05-31 13:26:56,690 INFO [test01.py(test01:27)] - 正在执行调用执行数据：{'path': '/api/sys/login', 'method': 'post', 'headers': {'Content-Type': 'application/json'}, 'param_type': 'json', 'params': {'mobile': '13800000002', 'password': '654321'}, 'expect': {'code': 200, 'result': {'success': True, 'code': 100001, 'message': '操作成功！'}}, 'x_y': [2, 12]}
2022-05-31 13:26:56,690 INFO [api.py(run_method:57)] - 正在调用运行接口方法
2022-05-31 13:26:56,690 INFO [api.py(_post:39)] - 正在调用post请求方法
2022-05-31 13:26:56,967 INFO [common_assert.py(common_assert:16)] - 正在调用断言公共方法
2022-05-31 13:26:56,987 ERROR [test01.py(test01:39)] - 错误，原因：错误！响应 success：False 预期 success：True
2022-05-31 13:26:57,127 INFO [test01.py(test01:27)] - 正在执行调用执行数据：{'path': '/api/sys/login', 'method': 'post', 'headers': {'Content-Type': 'application/json'}, 'param_type': 'json', 'params': {'mobile': 'itheima', 'password': '123456'}, 'expect': {'code': 200, 'result': {'success': False, 'code': 20001, 'message': '用户名或密码错误'}}, 'x_y': [6, 12]}
2022-05-31 13:26:57,127 INFO [api.py(run_method:57)] - 正在调用运行接口方法
2022-05-31 13:26:57,127 INFO [api.py(_post:39)] - 正在调用post请求方法
2022-05-31 13:26:57,201 INFO [common_assert.py(common_assert:16)] - 正在调用断言公共方法
2022-05-31 13:26:57,228 INFO [test01.py(test01:27)] - 正在执行调用执行数据：{'path': '/api/sys/login', 'method': 'post', 'headers': {'Content-Type': 'application/json'}, 'param_type': 'json', 'params': {'mobile': '13800000002', 'password': ''}, 'expect': {'code': 200, 'result': {'success': False, 'code': 20001, 'message': '用户名或密码错误'}}, 'x_y': [7, 12]}
2022-05-31 13:26:57,229 INFO [api.py(run_method:57)] - 正在调用运行接口方法
2022-05-31 13:26:57,229 INFO [api.py(_post:39)] - 正在调用post请求方法
2022-05-31 13:26:57,302 INFO [common_assert.py(common_assert:16)] - 正在调用断言公共方法
2022-05-31 13:40:42,349 INFO [test01.py(test01:27)] - 正在执行调用执行数据：{'path': '/api/sys/login', 'method': 'post', 'headers': {'Content-Type': 'application/json'}, 'param_type': 'json', 'params': {'mobile': '13800000002', 'password': '123456'}, 'expect': {'code': 200, 'result': {'success': True, 'code': 100001, 'message': '操作成功！'}}, 'x_y': [2, 12]}
2022-05-31 13:40:42,349 INFO [api.py(run_method:57)] - 正在调用运行接口方法
2022-05-31 13:40:42,349 INFO [api.py(_post:39)] - 正在调用post请求方法
2022-05-31 13:40:42,429 INFO [common_assert.py(common_assert:16)] - 正在调用断言公共方法
2022-05-31 13:40:42,460 ERROR [test01.py(test01:39)] - 错误，原因：错误！响应 code：10000 预期 code：100001
2022-05-31 13:40:42,600 INFO [test01.py(test01:27)] - 正在执行调用执行数据：{'path': '/api/sys/login', 'method': 'post', 'headers': {'Content-Type': 'application/json'}, 'param_type': 'json', 'params': {'mobile': 'itheima', 'password': '123456'}, 'expect': {'code': 200, 'result': {'success': False, 'code': 20001, 'message': '用户名或密码错误'}}, 'x_y': [6, 12]}
2022-05-31 13:40:42,600 INFO [api.py(run_method:57)] - 正在调用运行接口方法
2022-05-31 13:40:42,600 INFO [api.py(_post:39)] - 正在调用post请求方法
2022-05-31 13:40:42,679 INFO [common_assert.py(common_assert:16)] - 正在调用断言公共方法
2022-05-31 13:40:42,710 INFO [test01.py(test01:27)] - 正在执行调用执行数据：{'path': '/api/sys/login', 'method': 'post', 'headers': {'Content-Type': 'application/json'}, 'param_type': 'json', 'params': {'mobile': '13800000002', 'password': ''}, 'expect': {'code': 200, 'result': {'success': False, 'code': 20001, 'message': '用户名或密码错误'}}, 'x_y': [7, 12]}
2022-05-31 13:40:42,710 INFO [api.py(run_method:57)] - 正在调用运行接口方法
2022-05-31 13:40:42,710 INFO [api.py(_post:39)] - 正在调用post请求方法
2022-05-31 13:40:42,788 INFO [common_assert.py(common_assert:16)] - 正在调用断言公共方法
2022-05-31 13:45:20,459 INFO [test01.py(test01:27)] - 正在执行调用执行数据：{'path': '/api/sys/login', 'method': 'post', 'headers': {'Content-Type': 'application/json'}, 'param_type': 'json', 'params': {'mobile': '13800000002', 'password': '123456'}, 'expect': {'success': True, 'code': 10000, 'message': '操作成功！', 'data': '02238bdc-da48-4616-8715-8c7159235b2f'}, 'x_y': [2, 12]}
2022-05-31 13:45:20,459 INFO [api.py(run_method:57)] - 正在调用运行接口方法
2022-05-31 13:45:20,459 INFO [api.py(_post:39)] - 正在调用post请求方法
2022-05-31 13:45:20,537 INFO [common_assert.py(common_assert:16)] - 正在调用断言公共方法
2022-05-31 13:45:20,553 ERROR [test01.py(test01:39)] - 错误，原因：错误！响应 code：200 预期code：10000
2022-05-31 13:45:20,678 INFO [test01.py(test01:27)] - 正在执行调用执行数据：{'path': '/api/sys/login', 'method': 'post', 'headers': {'Content-Type': 'application/json'}, 'param_type': 'json', 'params': {'mobile': 'itheima', 'password': '123456'}, 'expect': {'code': 200, 'result': {'success': False, 'code': 20001, 'message': '用户名或密码错误'}}, 'x_y': [6, 12]}
2022-05-31 13:45:20,678 INFO [api.py(run_method:57)] - 正在调用运行接口方法
2022-05-31 13:45:20,678 INFO [api.py(_post:39)] - 正在调用post请求方法
2022-05-31 13:45:20,758 INFO [common_assert.py(common_assert:16)] - 正在调用断言公共方法
2022-05-31 13:45:20,789 INFO [test01.py(test01:27)] - 正在执行调用执行数据：{'path': '/api/sys/login', 'method': 'post', 'headers': {'Content-Type': 'application/json'}, 'param_type': 'json', 'params': {'mobile': '13800000002', 'password': ''}, 'expect': {'code': 200, 'result': {'success': False, 'code': 20001, 'message': '用户名或密码错误'}}, 'x_y': [7, 12]}
2022-05-31 13:45:20,789 INFO [api.py(run_method:57)] - 正在调用运行接口方法
2022-05-31 13:45:20,789 INFO [api.py(_post:39)] - 正在调用post请求方法
2022-05-31 13:45:20,867 INFO [common_assert.py(common_assert:16)] - 正在调用断言公共方法
2022-05-31 13:55:19,065 INFO [test01.py(test01:27)] - 正在执行调用执行数据：{'path': '/api/sys/login', 'method': 'post', 'headers': {'Content-Type': 'application/json'}, 'param_type': 'json', 'params': {'mobile': '13800000002', 'password': '123456'}, 'expect': {'success': True, 'code': 10000, 'message': '操作成功！', 'data': '02238bdc-da48-4616-8715-8c7159235b2f'}, 'x_y': [2, 12]}
2022-05-31 13:55:19,065 INFO [api.py(run_method:57)] - 正在调用运行接口方法
2022-05-31 13:55:19,065 INFO [api.py(_post:39)] - 正在调用post请求方法
2022-05-31 13:55:19,354 INFO [common_assert.py(common_assert:16)] - 正在调用断言公共方法
2022-05-31 13:55:19,376 ERROR [test01.py(test01:39)] - 错误，原因：错误！响应 code：200 预期code：10000
2022-05-31 13:55:19,497 INFO [test01.py(test01:27)] - 正在执行调用执行数据：{'path': '/api/sys/login', 'method': 'post', 'headers': {'Content-Type': 'application/json'}, 'param_type': 'json', 'params': {'mobile': 'itheima', 'password': '123456'}, 'expect': {'code': 200, 'result': {'success': False, 'code': 20001, 'message': '用户名或密码错误'}}, 'x_y': [6, 12]}
2022-05-31 13:55:19,497 INFO [api.py(run_method:57)] - 正在调用运行接口方法
2022-05-31 13:55:19,497 INFO [api.py(_post:39)] - 正在调用post请求方法
2022-05-31 13:55:19,606 INFO [common_assert.py(common_assert:16)] - 正在调用断言公共方法
2022-05-31 13:55:19,630 INFO [test01.py(test01:27)] - 正在执行调用执行数据：{'path': '/api/sys/login', 'method': 'post', 'headers': {'Content-Type': 'application/json'}, 'param_type': 'json', 'params': {'mobile': '13800000002', 'password': ''}, 'expect': {'code': 200, 'result': {'success': False, 'code': 20001, 'message': '用户名或密码错误'}}, 'x_y': [7, 12]}
2022-05-31 13:55:19,630 INFO [api.py(run_method:57)] - 正在调用运行接口方法
2022-05-31 13:55:19,630 INFO [api.py(_post:39)] - 正在调用post请求方法
2022-05-31 13:55:19,710 INFO [common_assert.py(common_assert:16)] - 正在调用断言公共方法
2022-05-31 13:57:25,102 INFO [test01.py(test01:27)] - 正在执行调用执行数据：{'path': '/api/sys/login', 'method': 'post', 'headers': {'Content-Type': 'application/json'}, 'param_type': 'json', 'params': {'mobile': '13800000002', 'password': '123456'}, 'expect': {'success': True, 'code': 10000, 'message': '操作成功！', 'data': '02238bdc-da48-4616-8715-8c7159235b2f'}, 'x_y': [2, 12]}
2022-05-31 13:57:25,102 INFO [api.py(run_method:57)] - 正在调用运行接口方法
2022-05-31 13:57:25,102 INFO [api.py(_post:39)] - 正在调用post请求方法
2022-05-31 13:57:25,362 INFO [common_assert.py(common_assert:16)] - 正在调用断言公共方法
2022-05-31 13:57:25,382 ERROR [test01.py(test01:39)] - 错误，原因：'NoneType' object has no attribute 'get'
2022-05-31 13:57:25,529 INFO [test01.py(test01:27)] - 正在执行调用执行数据：{'path': '/api/sys/login', 'method': 'post', 'headers': {'Content-Type': 'application/json'}, 'param_type': 'json', 'params': {'mobile': 'itheima', 'password': '123456'}, 'expect': {'code': 200, 'result': {'success': False, 'code': 20001, 'message': '用户名或密码错误'}}, 'x_y': [6, 12]}
2022-05-31 13:57:25,529 INFO [api.py(run_method:57)] - 正在调用运行接口方法
2022-05-31 13:57:25,529 INFO [api.py(_post:39)] - 正在调用post请求方法
2022-05-31 13:57:25,622 INFO [common_assert.py(common_assert:16)] - 正在调用断言公共方法
2022-05-31 13:57:25,643 ERROR [test01.py(test01:39)] - 错误，原因：错误！响应 code：20001 预期code：200
2022-05-31 13:57:25,650 INFO [test01.py(test01:27)] - 正在执行调用执行数据：{'path': '/api/sys/login', 'method': 'post', 'headers': {'Content-Type': 'application/json'}, 'param_type': 'json', 'params': {'mobile': '13800000002', 'password': ''}, 'expect': {'code': 200, 'result': {'success': False, 'code': 20001, 'message': '用户名或密码错误'}}, 'x_y': [7, 12]}
2022-05-31 13:57:25,650 INFO [api.py(run_method:57)] - 正在调用运行接口方法
2022-05-31 13:57:25,651 INFO [api.py(_post:39)] - 正在调用post请求方法
2022-05-31 13:57:25,727 INFO [common_assert.py(common_assert:16)] - 正在调用断言公共方法
2022-05-31 13:57:25,749 ERROR [test01.py(test01:39)] - 错误，原因：错误！响应 code：20001 预期code：200
2022-05-31 13:59:00,075 INFO [test01.py(test01:27)] - 正在执行调用执行数据：{'path': '/api/sys/login', 'method': 'post', 'headers': {'Content-Type': 'application/json'}, 'param_type': 'json', 'params': {'mobile': '13800000002', 'password': '123456'}, 'expect': {'success': True, 'code': 10000, 'message': '操作成功！', 'data': '02238bdc-da48-4616-8715-8c7159235b2f'}, 'x_y': [2, 12]}
2022-05-31 13:59:00,075 INFO [api.py(run_method:57)] - 正在调用运行接口方法
2022-05-31 13:59:00,075 INFO [api.py(_post:39)] - 正在调用post请求方法
2022-05-31 13:59:00,238 INFO [common_assert.py(common_assert:16)] - 正在调用断言公共方法
2022-05-31 13:59:00,238 INFO [common_assert.py(common_assert:21)] - {'success': True, 'code': 10000, 'message': '操作成功！', 'data': 'bbda6bdf-674a-4bd3-b4f5-b8ee1afe72ef'}
2022-05-31 13:59:00,261 ERROR [test01.py(test01:39)] - 错误，原因：'NoneType' object has no attribute 'get'
2022-05-31 13:59:00,408 INFO [test01.py(test01:27)] - 正在执行调用执行数据：{'path': '/api/sys/login', 'method': 'post', 'headers': {'Content-Type': 'application/json'}, 'param_type': 'json', 'params': {'mobile': 'itheima', 'password': '123456'}, 'expect': {'code': 200, 'result': {'success': False, 'code': 20001, 'message': '用户名或密码错误'}}, 'x_y': [6, 12]}
2022-05-31 13:59:00,408 INFO [api.py(run_method:57)] - 正在调用运行接口方法
2022-05-31 13:59:00,408 INFO [api.py(_post:39)] - 正在调用post请求方法
2022-05-31 13:59:00,491 INFO [common_assert.py(common_assert:16)] - 正在调用断言公共方法
2022-05-31 13:59:00,491 INFO [common_assert.py(common_assert:21)] - {'success': False, 'code': 20001, 'message': '用户名或密码错误', 'data': None}
2022-05-31 13:59:00,519 ERROR [test01.py(test01:39)] - 错误，原因：错误！响应 code：20001 预期code：200
2022-05-31 13:59:00,527 INFO [test01.py(test01:27)] - 正在执行调用执行数据：{'path': '/api/sys/login', 'method': 'post', 'headers': {'Content-Type': 'application/json'}, 'param_type': 'json', 'params': {'mobile': '13800000002', 'password': ''}, 'expect': {'code': 200, 'result': {'success': False, 'code': 20001, 'message': '用户名或密码错误'}}, 'x_y': [7, 12]}
2022-05-31 13:59:00,528 INFO [api.py(run_method:57)] - 正在调用运行接口方法
2022-05-31 13:59:00,528 INFO [api.py(_post:39)] - 正在调用post请求方法
2022-05-31 13:59:00,617 INFO [common_assert.py(common_assert:16)] - 正在调用断言公共方法
2022-05-31 13:59:00,617 INFO [common_assert.py(common_assert:21)] - {'success': False, 'code': 20001, 'message': '用户名或密码错误', 'data': None}
2022-05-31 13:59:00,640 ERROR [test01.py(test01:39)] - 错误，原因：错误！响应 code：20001 预期code：200
2022-05-31 14:01:35,168 INFO [test01.py(test01:27)] - 正在执行调用执行数据：{'path': '/api/sys/login', 'method': 'post', 'headers': {'Content-Type': 'application/json'}, 'param_type': 'json', 'params': {'mobile': '13800000002', 'password': '123456'}, 'expect': {'success': True, 'code': 10000, 'message': '操作成功！', 'data': '02238bdc-da48-4616-8715-8c7159235b2f'}, 'x_y': [2, 12]}
2022-05-31 14:01:35,168 INFO [api.py(run_method:57)] - 正在调用运行接口方法
2022-05-31 14:01:35,168 INFO [api.py(_post:39)] - 正在调用post请求方法
2022-05-31 14:01:35,257 INFO [common_assert.py(common_assert:16)] - 正在调用断言公共方法
2022-05-31 14:01:35,300 ERROR [test01.py(test01:39)] - 错误，原因：not all arguments converted during string formatting
2022-05-31 14:01:35,555 INFO [test01.py(test01:27)] - 正在执行调用执行数据：{'path': '/api/sys/login', 'method': 'post', 'headers': {'Content-Type': 'application/json'}, 'param_type': 'json', 'params': {'mobile': 'itheima', 'password': '123456'}, 'expect': {'code': 200, 'result': {'success': False, 'code': 20001, 'message': '用户名或密码错误'}}, 'x_y': [6, 12]}
2022-05-31 14:01:35,556 INFO [api.py(run_method:57)] - 正在调用运行接口方法
2022-05-31 14:01:35,556 INFO [api.py(_post:39)] - 正在调用post请求方法
2022-05-31 14:01:35,633 INFO [common_assert.py(common_assert:16)] - 正在调用断言公共方法
2022-05-31 14:01:35,658 ERROR [test01.py(test01:39)] - 错误，原因：not all arguments converted during string formatting
2022-05-31 14:01:35,782 INFO [test01.py(test01:27)] - 正在执行调用执行数据：{'path': '/api/sys/login', 'method': 'post', 'headers': {'Content-Type': 'application/json'}, 'param_type': 'json', 'params': {'mobile': '13800000002', 'password': ''}, 'expect': {'code': 200, 'result': {'success': False, 'code': 20001, 'message': '用户名或密码错误'}}, 'x_y': [7, 12]}
2022-05-31 14:01:35,782 INFO [api.py(run_method:57)] - 正在调用运行接口方法
2022-05-31 14:01:35,782 INFO [api.py(_post:39)] - 正在调用post请求方法
2022-05-31 14:01:35,859 INFO [common_assert.py(common_assert:16)] - 正在调用断言公共方法
2022-05-31 14:01:35,883 ERROR [test01.py(test01:39)] - 错误，原因：not all arguments converted during string formatting
2022-05-31 14:01:40,626 INFO [test01.py(test01:27)] - 正在执行调用执行数据：{'path': '/api/sys/login', 'method': 'post', 'headers': {'Content-Type': 'application/json'}, 'param_type': 'json', 'params': {'mobile': '13800000002', 'password': '123456'}, 'expect': {'success': True, 'code': 10000, 'message': '操作成功！', 'data': '02238bdc-da48-4616-8715-8c7159235b2f'}, 'x_y': [2, 12]}
2022-05-31 14:01:40,626 INFO [api.py(run_method:57)] - 正在调用运行接口方法
2022-05-31 14:01:40,627 INFO [api.py(_post:39)] - 正在调用post请求方法
2022-05-31 14:01:40,853 INFO [common_assert.py(common_assert:16)] - 正在调用断言公共方法
2022-05-31 14:01:40,876 ERROR [test01.py(test01:39)] - 错误，原因：not all arguments converted during string formatting
2022-05-31 14:01:41,124 INFO [test01.py(test01:27)] - 正在执行调用执行数据：{'path': '/api/sys/login', 'method': 'post', 'headers': {'Content-Type': 'application/json'}, 'param_type': 'json', 'params': {'mobile': 'itheima', 'password': '123456'}, 'expect': {'code': 200, 'result': {'success': False, 'code': 20001, 'message': '用户名或密码错误'}}, 'x_y': [6, 12]}
2022-05-31 14:01:41,124 INFO [api.py(run_method:57)] - 正在调用运行接口方法
2022-05-31 14:01:41,124 INFO [api.py(_post:39)] - 正在调用post请求方法
2022-05-31 14:01:41,216 INFO [common_assert.py(common_assert:16)] - 正在调用断言公共方法
2022-05-31 14:01:41,236 ERROR [test01.py(test01:39)] - 错误，原因：not all arguments converted during string formatting
2022-05-31 14:01:41,373 INFO [test01.py(test01:27)] - 正在执行调用执行数据：{'path': '/api/sys/login', 'method': 'post', 'headers': {'Content-Type': 'application/json'}, 'param_type': 'json', 'params': {'mobile': '13800000002', 'password': ''}, 'expect': {'code': 200, 'result': {'success': False, 'code': 20001, 'message': '用户名或密码错误'}}, 'x_y': [7, 12]}
2022-05-31 14:01:41,373 INFO [api.py(run_method:57)] - 正在调用运行接口方法
2022-05-31 14:01:41,373 INFO [api.py(_post:39)] - 正在调用post请求方法
2022-05-31 14:01:41,449 INFO [common_assert.py(common_assert:16)] - 正在调用断言公共方法
2022-05-31 14:01:41,473 ERROR [test01.py(test01:39)] - 错误，原因：not all arguments converted during string formatting
2022-05-31 14:02:15,831 INFO [test01.py(test01:27)] - 正在执行调用执行数据：{'path': '/api/sys/login', 'method': 'post', 'headers': {'Content-Type': 'application/json'}, 'param_type': 'json', 'params': {'mobile': '13800000002', 'password': '123456'}, 'expect': {'success': True, 'code': 10000, 'message': '操作成功！', 'data': '02238bdc-da48-4616-8715-8c7159235b2f'}, 'x_y': [2, 12]}
2022-05-31 14:02:15,831 INFO [api.py(run_method:57)] - 正在调用运行接口方法
2022-05-31 14:02:15,831 INFO [api.py(_post:39)] - 正在调用post请求方法
2022-05-31 14:02:16,184 INFO [common_assert.py(common_assert:16)] - 正在调用断言公共方法
2022-05-31 14:02:16,205 ERROR [test01.py(test01:39)] - 错误，原因：can only concatenate str (not "int") to str
2022-05-31 14:02:16,331 INFO [test01.py(test01:27)] - 正在执行调用执行数据：{'path': '/api/sys/login', 'method': 'post', 'headers': {'Content-Type': 'application/json'}, 'param_type': 'json', 'params': {'mobile': 'itheima', 'password': '123456'}, 'expect': {'code': 200, 'result': {'success': False, 'code': 20001, 'message': '用户名或密码错误'}}, 'x_y': [6, 12]}
2022-05-31 14:02:16,331 INFO [api.py(run_method:57)] - 正在调用运行接口方法
2022-05-31 14:02:16,331 INFO [api.py(_post:39)] - 正在调用post请求方法
2022-05-31 14:02:16,408 INFO [common_assert.py(common_assert:16)] - 正在调用断言公共方法
2022-05-31 14:02:16,429 ERROR [test01.py(test01:39)] - 错误，原因：can only concatenate str (not "int") to str
2022-05-31 14:02:16,436 INFO [test01.py(test01:27)] - 正在执行调用执行数据：{'path': '/api/sys/login', 'method': 'post', 'headers': {'Content-Type': 'application/json'}, 'param_type': 'json', 'params': {'mobile': '13800000002', 'password': ''}, 'expect': {'code': 200, 'result': {'success': False, 'code': 20001, 'message': '用户名或密码错误'}}, 'x_y': [7, 12]}
2022-05-31 14:02:16,436 INFO [api.py(run_method:57)] - 正在调用运行接口方法
2022-05-31 14:02:16,436 INFO [api.py(_post:39)] - 正在调用post请求方法
2022-05-31 14:02:16,536 INFO [common_assert.py(common_assert:16)] - 正在调用断言公共方法
2022-05-31 14:02:16,556 ERROR [test01.py(test01:39)] - 错误，原因：can only concatenate str (not "int") to str
2022-05-31 14:02:33,109 INFO [test01.py(test01:27)] - 正在执行调用执行数据：{'path': '/api/sys/login', 'method': 'post', 'headers': {'Content-Type': 'application/json'}, 'param_type': 'json', 'params': {'mobile': '13800000002', 'password': '123456'}, 'expect': {'success': True, 'code': 10000, 'message': '操作成功！', 'data': '02238bdc-da48-4616-8715-8c7159235b2f'}, 'x_y': [2, 12]}
2022-05-31 14:02:33,109 INFO [api.py(run_method:57)] - 正在调用运行接口方法
2022-05-31 14:02:33,109 INFO [api.py(_post:39)] - 正在调用post请求方法
2022-05-31 14:02:33,328 INFO [common_assert.py(common_assert:16)] - 正在调用断言公共方法
2022-05-31 14:02:33,328 INFO [common_assert.py(common_assert:21)] - code===10000
2022-05-31 14:02:33,354 ERROR [test01.py(test01:39)] - 错误，原因：'NoneType' object has no attribute 'get'
2022-05-31 14:02:33,499 INFO [test01.py(test01:27)] - 正在执行调用执行数据：{'path': '/api/sys/login', 'method': 'post', 'headers': {'Content-Type': 'application/json'}, 'param_type': 'json', 'params': {'mobile': 'itheima', 'password': '123456'}, 'expect': {'code': 200, 'result': {'success': False, 'code': 20001, 'message': '用户名或密码错误'}}, 'x_y': [6, 12]}
2022-05-31 14:02:33,499 INFO [api.py(run_method:57)] - 正在调用运行接口方法
2022-05-31 14:02:33,499 INFO [api.py(_post:39)] - 正在调用post请求方法
2022-05-31 14:02:33,575 INFO [common_assert.py(common_assert:16)] - 正在调用断言公共方法
2022-05-31 14:02:33,575 INFO [common_assert.py(common_assert:21)] - code===20001
2022-05-31 14:02:33,601 INFO [test01.py(test01:27)] - 正在执行调用执行数据：{'path': '/api/sys/login', 'method': 'post', 'headers': {'Content-Type': 'application/json'}, 'param_type': 'json', 'params': {'mobile': '13800000002', 'password': ''}, 'expect': {'code': 200, 'result': {'success': False, 'code': 20001, 'message': '用户名或密码错误'}}, 'x_y': [7, 12]}
2022-05-31 14:02:33,602 INFO [api.py(run_method:57)] - 正在调用运行接口方法
2022-05-31 14:02:33,602 INFO [api.py(_post:39)] - 正在调用post请求方法
2022-05-31 14:02:33,672 INFO [common_assert.py(common_assert:16)] - 正在调用断言公共方法
2022-05-31 14:02:33,672 INFO [common_assert.py(common_assert:21)] - code===20001
2022-05-31 14:03:00,913 INFO [test01.py(test01:27)] - 正在执行调用执行数据：{'path': '/api/sys/login', 'method': 'post', 'headers': {'Content-Type': 'application/json'}, 'param_type': 'json', 'params': {'mobile': '13800000002', 'password': '123456'}, 'expect': {'success': True, 'code': 10000, 'message': '操作成功！', 'data': '02238bdc-da48-4616-8715-8c7159235b2f'}, 'x_y': [2, 12]}
2022-05-31 14:03:00,913 INFO [api.py(run_method:57)] - 正在调用运行接口方法
2022-05-31 14:03:00,913 INFO [api.py(_post:39)] - 正在调用post请求方法
2022-05-31 14:03:01,085 INFO [common_assert.py(common_assert:16)] - 正在调用断言公共方法
2022-05-31 14:03:01,085 INFO [common_assert.py(common_assert:21)] - code===10000
2022-05-31 14:03:01,106 ERROR [test01.py(test01:39)] - 错误，原因：'NoneType' object has no attribute 'get'
2022-05-31 14:03:01,239 INFO [test01.py(test01:27)] - 正在执行调用执行数据：{'path': '/api/sys/login', 'method': 'post', 'headers': {'Content-Type': 'application/json'}, 'param_type': 'json', 'params': {'mobile': 'itheima', 'password': '123456'}, 'expect': {'code': 200, 'result': {'success': False, 'code': 20001, 'message': '用户名或密码错误'}}, 'x_y': [6, 12]}
2022-05-31 14:03:01,240 INFO [api.py(run_method:57)] - 正在调用运行接口方法
2022-05-31 14:03:01,240 INFO [api.py(_post:39)] - 正在调用post请求方法
2022-05-31 14:03:01,318 INFO [common_assert.py(common_assert:16)] - 正在调用断言公共方法
2022-05-31 14:03:01,318 INFO [common_assert.py(common_assert:21)] - code===20001
2022-05-31 14:03:01,342 INFO [test01.py(test01:27)] - 正在执行调用执行数据：{'path': '/api/sys/login', 'method': 'post', 'headers': {'Content-Type': 'application/json'}, 'param_type': 'json', 'params': {'mobile': '13800000002', 'password': ''}, 'expect': {'code': 200, 'result': {'success': False, 'code': 20001, 'message': '用户名或密码错误'}}, 'x_y': [7, 12]}
2022-05-31 14:03:01,342 INFO [api.py(run_method:57)] - 正在调用运行接口方法
2022-05-31 14:03:01,342 INFO [api.py(_post:39)] - 正在调用post请求方法
2022-05-31 14:03:01,413 INFO [common_assert.py(common_assert:16)] - 正在调用断言公共方法
2022-05-31 14:03:01,413 INFO [common_assert.py(common_assert:21)] - code===20001
2022-05-31 14:03:13,314 INFO [test01.py(test01:27)] - 正在执行调用执行数据：{'path': '/api/sys/login', 'method': 'post', 'headers': {'Content-Type': 'application/json'}, 'param_type': 'json', 'params': {'mobile': '13800000002', 'password': '123456'}, 'expect': {'success': True, 'code': 10000, 'message': '操作成功！', 'data': '02238bdc-da48-4616-8715-8c7159235b2f'}, 'x_y': [2, 12]}
2022-05-31 14:03:13,314 INFO [api.py(run_method:57)] - 正在调用运行接口方法
2022-05-31 14:03:13,315 INFO [api.py(_post:39)] - 正在调用post请求方法
2022-05-31 14:03:13,486 INFO [common_assert.py(common_assert:16)] - 正在调用断言公共方法
2022-05-31 14:03:13,510 ERROR [test01.py(test01:39)] - 错误，原因：'NoneType' object has no attribute 'get'
2022-05-31 14:03:13,673 INFO [test01.py(test01:27)] - 正在执行调用执行数据：{'path': '/api/sys/login', 'method': 'post', 'headers': {'Content-Type': 'application/json'}, 'param_type': 'json', 'params': {'mobile': 'itheima', 'password': '123456'}, 'expect': {'code': 200, 'result': {'success': False, 'code': 20001, 'message': '用户名或密码错误'}}, 'x_y': [6, 12]}
2022-05-31 14:03:13,673 INFO [api.py(run_method:57)] - 正在调用运行接口方法
2022-05-31 14:03:13,673 INFO [api.py(_post:39)] - 正在调用post请求方法
2022-05-31 14:03:13,755 INFO [common_assert.py(common_assert:16)] - 正在调用断言公共方法
2022-05-31 14:03:13,778 INFO [test01.py(test01:27)] - 正在执行调用执行数据：{'path': '/api/sys/login', 'method': 'post', 'headers': {'Content-Type': 'application/json'}, 'param_type': 'json', 'params': {'mobile': '13800000002', 'password': ''}, 'expect': {'code': 200, 'result': {'success': False, 'code': 20001, 'message': '用户名或密码错误'}}, 'x_y': [7, 12]}
2022-05-31 14:03:13,778 INFO [api.py(run_method:57)] - 正在调用运行接口方法
2022-05-31 14:03:13,779 INFO [api.py(_post:39)] - 正在调用post请求方法
2022-05-31 14:03:13,856 INFO [common_assert.py(common_assert:16)] - 正在调用断言公共方法
2022-05-31 14:03:58,380 INFO [test01.py(test01:27)] - 正在执行调用执行数据：{'path': '/api/sys/login', 'method': 'post', 'headers': {'Content-Type': 'application/json'}, 'param_type': 'json', 'params': {'mobile': '13800000002', 'password': '123456'}, 'expect': {'success': True, 'code': 10000, 'message': '操作成功！', 'data': '02238bdc-da48-4616-8715-8c7159235b2f'}, 'x_y': [2, 12]}
2022-05-31 14:03:58,380 INFO [api.py(run_method:57)] - 正在调用运行接口方法
2022-05-31 14:03:58,380 INFO [api.py(_post:39)] - 正在调用post请求方法
2022-05-31 14:03:58,493 INFO [common_assert.py(common_assert:16)] - 正在调用断言公共方法
2022-05-31 14:03:58,517 ERROR [test01.py(test01:39)] - 错误，原因：错误！响应 code：200 预期code：10000
2022-05-31 14:03:58,665 INFO [test01.py(test01:27)] - 正在执行调用执行数据：{'path': '/api/sys/login', 'method': 'post', 'headers': {'Content-Type': 'application/json'}, 'param_type': 'json', 'params': {'mobile': 'itheima', 'password': '123456'}, 'expect': {'code': 200, 'result': {'success': False, 'code': 20001, 'message': '用户名或密码错误'}}, 'x_y': [6, 12]}
2022-05-31 14:03:58,665 INFO [api.py(run_method:57)] - 正在调用运行接口方法
2022-05-31 14:03:58,665 INFO [api.py(_post:39)] - 正在调用post请求方法
2022-05-31 14:03:58,744 INFO [common_assert.py(common_assert:16)] - 正在调用断言公共方法
2022-05-31 14:03:58,769 INFO [test01.py(test01:27)] - 正在执行调用执行数据：{'path': '/api/sys/login', 'method': 'post', 'headers': {'Content-Type': 'application/json'}, 'param_type': 'json', 'params': {'mobile': '13800000002', 'password': ''}, 'expect': {'code': 200, 'result': {'success': False, 'code': 20001, 'message': '用户名或密码错误'}}, 'x_y': [7, 12]}
2022-05-31 14:03:58,769 INFO [api.py(run_method:57)] - 正在调用运行接口方法
2022-05-31 14:03:58,769 INFO [api.py(_post:39)] - 正在调用post请求方法
2022-05-31 14:03:58,847 INFO [common_assert.py(common_assert:16)] - 正在调用断言公共方法
2022-05-31 14:04:36,701 INFO [test01.py(test01:27)] - 正在执行调用执行数据：{'path': '/api/sys/login', 'method': 'post', 'headers': {'Content-Type': 'application/json'}, 'param_type': 'json', 'params': {'mobile': '13800000002', 'password': '123456'}, 'expect': {'success': True, 'code': 10000, 'message': '操作成功！', 'data': '02238bdc-da48-4616-8715-8c7159235b2f'}, 'x_y': [2, 12]}
2022-05-31 14:04:36,701 INFO [api.py(run_method:57)] - 正在调用运行接口方法
2022-05-31 14:04:36,701 INFO [api.py(_post:39)] - 正在调用post请求方法
2022-05-31 14:04:36,786 INFO [common_assert.py(common_assert:16)] - 正在调用断言公共方法
2022-05-31 14:04:36,808 ERROR [test01.py(test01:39)] - 错误，原因：'NoneType' object has no attribute 'get'
2022-05-31 14:04:36,957 INFO [test01.py(test01:27)] - 正在执行调用执行数据：{'path': '/api/sys/login', 'method': 'post', 'headers': {'Content-Type': 'application/json'}, 'param_type': 'json', 'params': {'mobile': 'itheima', 'password': '123456'}, 'expect': {'code': 200, 'result': {'success': False, 'code': 20001, 'message': '用户名或密码错误'}}, 'x_y': [6, 12]}
2022-05-31 14:04:36,957 INFO [api.py(run_method:57)] - 正在调用运行接口方法
2022-05-31 14:04:36,958 INFO [api.py(_post:39)] - 正在调用post请求方法
2022-05-31 14:04:37,033 INFO [common_assert.py(common_assert:16)] - 正在调用断言公共方法
2022-05-31 14:04:37,058 INFO [test01.py(test01:27)] - 正在执行调用执行数据：{'path': '/api/sys/login', 'method': 'post', 'headers': {'Content-Type': 'application/json'}, 'param_type': 'json', 'params': {'mobile': '13800000002', 'password': ''}, 'expect': {'code': 200, 'result': {'success': False, 'code': 20001, 'message': '用户名或密码错误'}}, 'x_y': [7, 12]}
2022-05-31 14:04:37,058 INFO [api.py(run_method:57)] - 正在调用运行接口方法
2022-05-31 14:04:37,058 INFO [api.py(_post:39)] - 正在调用post请求方法
2022-05-31 14:04:37,132 INFO [common_assert.py(common_assert:16)] - 正在调用断言公共方法
2022-05-31 14:07:13,850 INFO [test01.py(test01:27)] - 正在执行调用执行数据：{'path': '/api/sys/login', 'method': 'post', 'headers': {'Content-Type': 'application/json'}, 'param_type': 'json', 'params': {'mobile': '13800000002', 'password': '123456'}, 'expect': {'success': True, 'code': 10000, 'message': '操作成功！', 'data': '02238bdc-da48-4616-8715-8c7159235b2f'}, 'x_y': [2, 12]}
2022-05-31 14:07:13,850 INFO [api.py(run_method:57)] - 正在调用运行接口方法
2022-05-31 14:07:13,850 INFO [api.py(_post:39)] - 正在调用post请求方法
2022-05-31 14:07:13,992 INFO [common_assert.py(common_assert:16)] - 正在调用断言公共方法
2022-05-31 14:07:14,022 ERROR [test01.py(test01:39)] - 错误，原因：'NoneType' object has no attribute 'get'
2022-05-31 14:07:14,170 INFO [test01.py(test01:27)] - 正在执行调用执行数据：{'path': '/api/sys/login', 'method': 'post', 'headers': {'Content-Type': 'application/json'}, 'param_type': 'json', 'params': {'mobile': 'itheima', 'password': '123456'}, 'expect': {'code': 200, 'result': {'success': False, 'code': 20001, 'message': '用户名或密码错误'}}, 'x_y': [6, 12]}
2022-05-31 14:07:14,170 INFO [api.py(run_method:57)] - 正在调用运行接口方法
2022-05-31 14:07:14,171 INFO [api.py(_post:39)] - 正在调用post请求方法
2022-05-31 14:07:14,246 INFO [common_assert.py(common_assert:16)] - 正在调用断言公共方法
2022-05-31 14:07:14,272 ERROR [test01.py(test01:39)] - 错误，原因：错误！响应 success：False 预期 success：None
2022-05-31 14:07:14,282 INFO [test01.py(test01:27)] - 正在执行调用执行数据：{'path': '/api/sys/login', 'method': 'post', 'headers': {'Content-Type': 'application/json'}, 'param_type': 'json', 'params': {'mobile': '13800000002', 'password': ''}, 'expect': {'code': 200, 'result': {'success': False, 'code': 20001, 'message': '用户名或密码错误'}}, 'x_y': [7, 12]}
2022-05-31 14:07:14,282 INFO [api.py(run_method:57)] - 正在调用运行接口方法
2022-05-31 14:07:14,283 INFO [api.py(_post:39)] - 正在调用post请求方法
2022-05-31 14:07:14,361 INFO [common_assert.py(common_assert:16)] - 正在调用断言公共方法
2022-05-31 14:07:14,382 ERROR [test01.py(test01:39)] - 错误，原因：错误！响应 success：False 预期 success：None
2022-05-31 14:08:10,685 INFO [test01.py(test01:27)] - 正在执行调用执行数据：{'path': '/api/sys/login', 'method': 'post', 'headers': {'Content-Type': 'application/json'}, 'param_type': 'json', 'params': {'mobile': '13800000002', 'password': '123456'}, 'expect': {'success': True, 'code': 10000, 'message': '操作成功！', 'data': '02238bdc-da48-4616-8715-8c7159235b2f'}, 'x_y': [2, 12]}
2022-05-31 14:08:10,685 INFO [api.py(run_method:57)] - 正在调用运行接口方法
2022-05-31 14:08:10,685 INFO [api.py(_post:39)] - 正在调用post请求方法
2022-05-31 14:08:10,780 INFO [common_assert.py(common_assert:16)] - 正在调用断言公共方法
2022-05-31 14:08:10,808 INFO [test01.py(test01:27)] - 正在执行调用执行数据：{'path': '/api/sys/login', 'method': 'post', 'headers': {'Content-Type': 'application/json'}, 'param_type': 'json', 'params': {'mobile': 'itheima', 'password': '123456'}, 'expect': {'code': 200, 'result': {'success': False, 'code': 20001, 'message': '用户名或密码错误'}}, 'x_y': [6, 12]}
2022-05-31 14:08:10,808 INFO [api.py(run_method:57)] - 正在调用运行接口方法
2022-05-31 14:08:10,808 INFO [api.py(_post:39)] - 正在调用post请求方法
2022-05-31 14:08:10,884 INFO [common_assert.py(common_assert:16)] - 正在调用断言公共方法
2022-05-31 14:08:10,904 ERROR [test01.py(test01:39)] - 错误，原因：错误！响应 success：False 预期 success：None
2022-05-31 14:08:11,370 INFO [test01.py(test01:27)] - 正在执行调用执行数据：{'path': '/api/sys/login', 'method': 'post', 'headers': {'Content-Type': 'application/json'}, 'param_type': 'json', 'params': {'mobile': '13800000002', 'password': ''}, 'expect': {'code': 200, 'result': {'success': False, 'code': 20001, 'message': '用户名或密码错误'}}, 'x_y': [7, 12]}
2022-05-31 14:08:11,370 INFO [api.py(run_method:57)] - 正在调用运行接口方法
2022-05-31 14:08:11,371 INFO [api.py(_post:39)] - 正在调用post请求方法
2022-05-31 14:08:11,449 INFO [common_assert.py(common_assert:16)] - 正在调用断言公共方法
2022-05-31 14:08:11,471 ERROR [test01.py(test01:39)] - 错误，原因：错误！响应 success：False 预期 success：None
2022-05-31 14:13:32,071 INFO [test01.py(test01:27)] - 正在执行调用执行数据：{'path': '/api/sys/login', 'method': 'post', 'headers': {'Content-Type': 'application/json'}, 'param_type': 'json', 'params': {'mobile': '13800000002', 'password': '123456'}, 'expect': {'success': True, 'code': 10000, 'message': '操作成功！', 'data': '02238bdc-da48-4616-8715-8c7159235b2f'}, 'x_y': [2, 12]}
2022-05-31 14:13:32,071 INFO [api.py(run_method:57)] - 正在调用运行接口方法
2022-05-31 14:13:32,071 INFO [api.py(_post:39)] - 正在调用post请求方法
2022-05-31 14:13:32,333 INFO [common_assert.py(common_assert:16)] - 正在调用断言公共方法
2022-05-31 14:13:32,358 ERROR [test01.py(test01:39)] - 错误，原因：'RootLogger' object is not callable
2022-05-31 14:13:32,499 INFO [test01.py(test01:27)] - 正在执行调用执行数据：{'path': '/api/sys/login', 'method': 'post', 'headers': {'Content-Type': 'application/json'}, 'param_type': 'json', 'params': {'mobile': 'itheima', 'password': '123456'}, 'expect': {'code': 200, 'result': {'success': False, 'code': 20001, 'message': '用户名或密码错误'}}, 'x_y': [6, 12]}
2022-05-31 14:13:32,499 INFO [api.py(run_method:57)] - 正在调用运行接口方法
2022-05-31 14:13:32,499 INFO [api.py(_post:39)] - 正在调用post请求方法
2022-05-31 14:13:32,576 INFO [common_assert.py(common_assert:16)] - 正在调用断言公共方法
2022-05-31 14:13:32,599 ERROR [test01.py(test01:39)] - 错误，原因：'RootLogger' object is not callable
2022-05-31 14:13:32,607 INFO [test01.py(test01:27)] - 正在执行调用执行数据：{'path': '/api/sys/login', 'method': 'post', 'headers': {'Content-Type': 'application/json'}, 'param_type': 'json', 'params': {'mobile': '13800000002', 'password': ''}, 'expect': {'code': 200, 'result': {'success': False, 'code': 20001, 'message': '用户名或密码错误'}}, 'x_y': [7, 12]}
2022-05-31 14:13:32,608 INFO [api.py(run_method:57)] - 正在调用运行接口方法
2022-05-31 14:13:32,608 INFO [api.py(_post:39)] - 正在调用post请求方法
2022-05-31 14:13:32,692 INFO [common_assert.py(common_assert:16)] - 正在调用断言公共方法
2022-05-31 14:13:32,712 ERROR [test01.py(test01:39)] - 错误，原因：'RootLogger' object is not callable
2022-05-31 14:15:45,310 INFO [test01.py(test01:27)] - 正在执行调用执行数据：{'path': '/api/sys/login', 'method': 'post', 'headers': {'Content-Type': 'application/json'}, 'param_type': 'json', 'params': {'mobile': '13800000002', 'password': '123456'}, 'expect': {'success': True, 'code': 10000, 'message': '操作成功！', 'data': '02238bdc-da48-4616-8715-8c7159235b2f'}, 'x_y': [2, 12]}
2022-05-31 14:15:45,310 INFO [api.py(run_method:57)] - 正在调用运行接口方法
2022-05-31 14:15:45,311 INFO [api.py(_post:39)] - 正在调用post请求方法
2022-05-31 14:15:45,406 INFO [common_assert.py(common_assert:16)] - 正在调用断言公共方法
2022-05-31 14:15:45,430 INFO [test01.py(test01:27)] - 正在执行调用执行数据：{'path': '/api/sys/login', 'method': 'post', 'headers': {'Content-Type': 'application/json'}, 'param_type': 'json', 'params': {'mobile': 'itheima', 'password': '123456'}, 'expect': {'code': 200, 'result': {'success': False, 'code': 20001, 'message': '用户名或密码错误'}}, 'x_y': [6, 12]}
2022-05-31 14:15:45,430 INFO [api.py(run_method:57)] - 正在调用运行接口方法
2022-05-31 14:15:45,430 INFO [api.py(_post:39)] - 正在调用post请求方法
2022-05-31 14:15:45,510 INFO [common_assert.py(common_assert:16)] - 正在调用断言公共方法
2022-05-31 14:15:45,530 ERROR [test01.py(test01:39)] - 错误，原因：错误！响应 success：False 预期 success：None
2022-05-31 14:15:45,668 INFO [test01.py(test01:27)] - 正在执行调用执行数据：{'path': '/api/sys/login', 'method': 'post', 'headers': {'Content-Type': 'application/json'}, 'param_type': 'json', 'params': {'mobile': '13800000002', 'password': ''}, 'expect': {'code': 200, 'result': {'success': False, 'code': 20001, 'message': '用户名或密码错误'}}, 'x_y': [7, 12]}
2022-05-31 14:15:45,668 INFO [api.py(run_method:57)] - 正在调用运行接口方法
2022-05-31 14:15:45,669 INFO [api.py(_post:39)] - 正在调用post请求方法
2022-05-31 14:15:45,743 INFO [common_assert.py(common_assert:16)] - 正在调用断言公共方法
2022-05-31 14:15:45,766 ERROR [test01.py(test01:39)] - 错误，原因：错误！响应 success：False 预期 success：None
2022-05-31 14:17:58,146 INFO [test01.py(test01:27)] - 正在执行调用执行数据：{'path': '/api/sys/login', 'method': 'post', 'headers': {'Content-Type': 'application/json'}, 'param_type': 'json', 'params': {'mobile': '13800000002', 'password': '123456'}, 'expect': {'success': True, 'code': 10000, 'message': '操作成功！', 'data': '02238bdc-da48-4616-8715-8c7159235b2f'}, 'x_y': [2, 12]}
2022-05-31 14:17:58,146 INFO [api.py(run_method:57)] - 正在调用运行接口方法
2022-05-31 14:17:58,146 INFO [api.py(_post:39)] - 正在调用post请求方法
2022-05-31 14:17:58,381 INFO [common_assert.py(common_assert:16)] - 正在调用断言公共方法
2022-05-31 14:17:58,412 INFO [test01.py(test01:27)] - 正在执行调用执行数据：{'path': '/api/sys/login', 'method': 'post', 'headers': {'Content-Type': 'application/json'}, 'param_type': 'json', 'params': {'mobile': 'itheima', 'password': '123456'}, 'expect': {'success': False, 'code': 20001, 'message': '用户名或密码错误', 'data': None}, 'x_y': [6, 12]}
2022-05-31 14:17:58,412 INFO [api.py(run_method:57)] - 正在调用运行接口方法
2022-05-31 14:17:58,412 INFO [api.py(_post:39)] - 正在调用post请求方法
2022-05-31 14:17:58,475 INFO [common_assert.py(common_assert:16)] - 正在调用断言公共方法
2022-05-31 14:17:58,506 INFO [test01.py(test01:27)] - 正在执行调用执行数据：{'path': '/api/sys/login', 'method': 'post', 'headers': {'Content-Type': 'application/json'}, 'param_type': 'json', 'params': {'mobile': '13800000002', 'password': ''}, 'expect': {'success': False, 'code': 20001, 'message': '用户名或密码错误', 'data': None}, 'x_y': [7, 12]}
2022-05-31 14:17:58,506 INFO [api.py(run_method:57)] - 正在调用运行接口方法
2022-05-31 14:17:58,506 INFO [api.py(_post:39)] - 正在调用post请求方法
2022-05-31 14:17:58,568 INFO [common_assert.py(common_assert:16)] - 正在调用断言公共方法
2022-05-31 16:03:34,840 INFO [test01.py(test01:27)] - 正在执行调用执行数据：{'path': '/api/sys/login', 'method': 'post', 'headers': {'Content-Type': 'application/json'}, 'param_type': 'json', 'params': {'mobile': '13800000002', 'password': '123456'}, 'expect': {'success': True, 'code': 10000, 'message': '操作成功！', 'data': '02238bdc-da48-4616-8715-8c7159235b2f'}, 'x_y': [2, 12]}
2022-05-31 16:03:34,840 INFO [api.py(run_method:57)] - 正在调用运行接口方法
2022-05-31 16:03:34,841 INFO [api.py(_post:39)] - 正在调用post请求方法
2022-05-31 16:05:22,238 INFO [test01.py(test01:27)] - 正在执行调用执行数据：{'path': '/api/sys/login', 'method': 'post', 'headers': {'Content-Type': 'application/json'}, 'param_type': 'json', 'params': {'mobile': '13800000002', 'password': '123456'}, 'expect': {'success': True, 'code': 10000, 'message': '操作成功！', 'data': '02238bdc-da48-4616-8715-8c7159235b2f'}, 'x_y': [2, 12]}
2022-05-31 16:05:22,239 INFO [api.py(run_method:57)] - 正在调用运行接口方法
2022-05-31 16:05:22,239 INFO [api.py(_post:39)] - 正在调用post请求方法
2022-05-31 16:05:22,321 INFO [common_assert.py(common_assert:16)] - 正在调用断言公共方法
2022-05-31 16:05:22,349 INFO [test01.py(test01:27)] - 正在执行调用执行数据：{'path': '/api/sys/login', 'method': 'post', 'headers': {'Content-Type': 'application/json'}, 'param_type': 'json', 'params': {'mobile': 'itheima', 'password': '123456'}, 'expect': {'success': False, 'code': 20001, 'message': '用户名或密码错误', 'data': None}, 'x_y': [6, 12]}
2022-05-31 16:05:22,350 INFO [api.py(run_method:57)] - 正在调用运行接口方法
2022-05-31 16:05:22,350 INFO [api.py(_post:39)] - 正在调用post请求方法
2022-05-31 16:05:22,437 INFO [common_assert.py(common_assert:16)] - 正在调用断言公共方法
2022-05-31 16:05:22,461 INFO [test01.py(test01:27)] - 正在执行调用执行数据：{'path': '/api/sys/login', 'method': 'post', 'headers': {'Content-Type': 'application/json'}, 'param_type': 'json', 'params': {'mobile': '13800000002', 'password': ''}, 'expect': {'success': False, 'code': 20001, 'message': '用户名或密码错误', 'data': None}, 'x_y': [7, 12]}
2022-05-31 16:05:22,461 INFO [api.py(run_method:57)] - 正在调用运行接口方法
2022-05-31 16:05:22,461 INFO [api.py(_post:39)] - 正在调用post请求方法
2022-05-31 16:05:22,537 INFO [common_assert.py(common_assert:16)] - 正在调用断言公共方法
2022-05-31 16:05:48,742 INFO [test01.py(test01:27)] - 正在执行调用执行数据：{'path': '/api/sys/login', 'method': 'post', 'headers': {'Content-Type': 'application/json'}, 'param_type': 'json', 'params': {'mobile': '13800000002', 'password': '123456'}, 'expect': {'success': True, 'code': 10000, 'message': '操作成功！', 'data': '02238bdc-da48-4616-8715-8c7159235b2f'}, 'x_y': [2, 12]}
2022-05-31 16:05:48,742 INFO [api.py(run_method:57)] - 正在调用运行接口方法
2022-05-31 16:05:48,742 INFO [api.py(_post:39)] - 正在调用post请求方法
2022-05-31 16:05:48,836 INFO [common_assert.py(common_assert:16)] - 正在调用断言公共方法
2022-05-31 16:05:48,863 INFO [test01.py(test01:27)] - 正在执行调用执行数据：{'path': '/api/sys/login', 'method': 'post', 'headers': {'Content-Type': 'application/json'}, 'param_type': 'json', 'params': {'mobile': 'itheima', 'password': '123456'}, 'expect': {'success': False, 'code': 20001, 'message': '用户名或密码错误', 'data': None}, 'x_y': [6, 12]}
2022-05-31 16:05:48,863 INFO [api.py(run_method:57)] - 正在调用运行接口方法
2022-05-31 16:05:48,863 INFO [api.py(_post:39)] - 正在调用post请求方法
2022-05-31 16:05:48,951 INFO [common_assert.py(common_assert:16)] - 正在调用断言公共方法
2022-05-31 16:05:48,978 INFO [test01.py(test01:27)] - 正在执行调用执行数据：{'path': '/api/sys/login', 'method': 'post', 'headers': {'Content-Type': 'application/json'}, 'param_type': 'json', 'params': {'mobile': '13800000002', 'password': ''}, 'expect': {'success': False, 'code': 20001, 'message': '用户名或密码错误', 'data': None}, 'x_y': [7, 12]}
2022-05-31 16:05:48,978 INFO [api.py(run_method:57)] - 正在调用运行接口方法
2022-05-31 16:05:48,979 INFO [api.py(_post:39)] - 正在调用post请求方法
2022-05-31 16:05:49,051 INFO [common_assert.py(common_assert:16)] - 正在调用断言公共方法
